# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
