# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 05:36
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160810_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latlng',
            field=models.CharField(default='37.4624015, 126.9520365', help_text='위도, 경도 포맷으로 입력', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Location'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(help_text='30분 이용 가격'),
        ),
    ]
