# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
