# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rating_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
